language: node_js
node_js: "10"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - gcc-multilib
    - g++-multilib
    - libc6-dev-i386
install:
- npm install
- npm update
script:
- ./scripts/make.sh
deploy:
- on:
    branch: master
    tags: true
    commits: false
  provider: releases
  api_key:
    secure: "M2GWFX8ePoIGz/2OaIa/rwYyocITz05WBMSi6cetduXutLc2FMICiaOu7HH42SRl2r+ZLsCGvO93RBevTZrq9LPnprGj9aTRfZIJQarv63g/+LG/lsS/VfkqyzweXWEl91fV6MJj+C/ClMlQ1QB3Q6xUqWG+iMmPmL8zpx1mvF+D4pLWUsMfx5mDtZ4UJXxux0pmBPVjCSqjGmP/nIEeK3WW2OL2n/wFMUQDVLV44w8XI0i6O7z191nt8XByrzyjz0fvwW8lzSsGgn6VZvfSJd9sNT3VOMqIFI7QWcWHSbyEqffXkgaPru1UG/udVD+FBcavl5sLxIW3gg4oguVsL0hvLa5B5QG3r8IXuauVNs7cnqWlHKZJVd2ZClgMBXwrqz2hqpr69FuEKRqzUUJUjQAvJgGrUuYQodAiZcRsf+Ba89NcAojm7FVXbftCmYnrKqu0iP1mFdHgEvLT7uKACpFlz712incOgCSYG/iD3cTJ9rrPT0lMiJJgjMXE/r6QqsPQMxo9AFJSoakz3e5nQqyT6+/61vdvwdPXwAP5sjUgVikCuYyj3N/PB4dWdNL0/Za49UBf1DahUwco5Jb9DRlHEXZ/hox0zdwuOMi09dp9nAKbcM8I70AN+m9zceUxzoHNJGqMWDDqWNyrQWNu5dcTHaOsRVcPSMVpOmY4j2o="
  file:
  - $TRAVIS_BUILD_DIR/out/make/myrpc-deb-i386.deb
  - $TRAVIS_BUILD_DIR/out/make/myrpc-deb.deb
  skip_cleanup: true