platform:
- x64
os: unstable
environment:
  GH_TOKEN:
    secure: YJjw6kA+aaI18k7YeHRNVR2+chHuahAg9ywUYEj2NPu9qumYOtw2Vmv/Ngx6Nodv
  nodejs_version: "10"
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update
test_script:
- node --version
- npm --version
- npm run lint
build_script:
- if %APPVEYOR_REPO_TAG% EQU false npm run make
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish