platform:
- x64
os: unstable
environment:
  GITHUB_TOKEN:
    secure: o3T+Z+BEcsw/K7sDBVQTo5ivGi+bjDw4kn4gbLbSbvm16NetB/0WwawSf3QiyNvf
  nodejs_version: "10"
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update
test_script:
- node --version
- npm --version
build_script:
- if %APPVEYOR_REPO_TAG% EQU false npm run make
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish
notifications:
  - provider: Webhook
    url:
      secure: WiPbRNc4K5PdxxAVucneOsum+z1QXHXyiA+/SpkZqrNV4XlTkajEfc6rvXDiK15JS2Tbyk9dozx5eHDvV4IZZDG96zLzDmEkl0Wa9y2IKa5uG1q6mv3NvW72EqWgTV5rEwLXJ5N+bVjSjXXQWSp1Vvk/ukq9he6iXaak1BFtl+w=
    method: POST