version: 1.0.0.{build}
image:
- Visual Studio 2017
- Ubuntu1804
environment:
	nodejs_version: "11"
install:
  - ps: Install-Product node $env:nodejs_version
	- npm install
build_script:
- npm run make
artifacts:
- path: MyRPC_v$(APPVEYOR_REPO_TAG_NAME)_Debian_x32.deb
	name: Deb32
- path: MyRPC_v$(APPVEYOR_REPO_TAG_NAME)_Debian_x64.deb
	name: Deb64
- path: MyRPC_v$(APPVEYOR_REPO_TAG_NAME)_Win32_x32.exe
	name: Win32
- path: MyRPC_v$(APPVEYOR_REPO_TAG_NAME)_Win32_x64.exe
	name: Win64
deploy:
	provider: GitHub
	tag: $(APPVEYOR_REPO_TAG_NAME)
	release: MyRPC $(AppVersion)
	description: "[Download](https://railrunner16.me/MyRPC/#downloads)\n[Patreon](https://www.patreon.com/railrunner16)\n[Discord](https://discord.gg/)"
	auth_token:
		secure: lB+qrk227SR4Y8i3Sr5tH+syVraqsZNroJUYli5t2tLV3tR8tg1TiZ6CA4Y4JXDn
	artifact: Deb32,Deb64,Win32,Win64
	draft: false
	prerelease: false
	on:
		configuration: Release
		appveyor_repo_tag: true